version: '3.1'

services:

  solr:
    image: 'devwithlando/pantheon-index:3.6-3'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - '8983:449'
    volumes:
      - './.docker/solr/schema.xml:/usr/share/solr/conf/schema.xml:delegated'
      - 'solrdata:/usr/share/solr/data'
    networks:
      - common-network

  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        set_time_limit(1000);
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true);
        define('SUBDOMAIN_INSTALL', false);
        define('DOMAIN_CURRENT_SITE', 'localhost:8080'); // Change to actual domain while deploying.
        define('PATH_CURRENT_SITE', '/');
        define('SITE_ID_CURRENT_SITE', 1);
        define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - wordpress:/var/www/html
    networks:
      - common-network
    depends_on:
      - db
      - solr
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: 'mariadb:latest'
    restart: always
    environment:
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - './.docker/mysql/my.cnf:/etc/mysql/my.cnf'
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  wordpress:
  db:
  solrdata: