version: '3.1'

services:

  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_CONFIG_EXTRA: |
        set_time_limit(1000);
        define('DOMAIN_CURRENT_SITE', 'localhost:8080'); // Change to actual domain while deploying.
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
    networks:
      - common-network
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: 'mariadb:latest'
    restart: always
    environment:
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - './.docker/mysql/my.cnf:/etc/mysql/my.cnf'
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  wordpress:
  db: