name: Backend Image build

on:
  push:
    branches:
      - master

jobs:
  buildImage:
    name: Build backend image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: './backend/plugins/souptik2001/.nvmrc'

      - name: Install WordPress plugins
        uses: php-actions/composer@v6
        with:
          command: composer install --working-dir=backend

      - name: Build the souptik2001 plugin's assets
        run: cd backend/plugins/souptik2001 && npm ci && npm run build && rm -rf node_modules

      - name: Build backend container image
        run: docker build ./backend --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Login to Container Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Github Container Repository
        run:
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
