name: Backend Image build

on: [push]

jobs:
  buildImage:
    name: Build backend image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build backend container image
        run: docker build ./backend --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Login to Container Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Github Container Repository
        run:
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
